# Generated by Django 5.2.9 on 2025-12-15 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('node_name', models.CharField(help_text='ESPHome node name (e.g., home1_livingroom_node1)', max_length=100, unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('file', models.FileField(upload_to='firmware/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OTAStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_history', to='devices.device')),
                ('firmware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.firmware')),
            ],
            options={
                'verbose_name': 'OTA Status',
                'verbose_name_plural': 'OTA Statuses',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(help_text='Entity name (e.g., living_room_fan)', max_length=50)),
                ('entity_type', models.CharField(choices=[('switch', 'Switch'), ('light', 'Light'), ('fan', 'Fan'), ('sensor', 'Sensor'), ('binary_sensor', 'Binary Sensor')], max_length=20)),
                ('gpio_pin', models.IntegerField(blank=True, help_text='GPIO pin number (if applicable)', null=True)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='devices.device')),
            ],
            options={
                'ordering': ['device', 'entity_type', 'entity_name'],
                'unique_together': {('device', 'entity_name')},
            },
        ),
        migrations.CreateModel(
            name='GPIOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_id', models.CharField(help_text='Logical identifier (e.g., relay_1)', max_length=32)),
                ('gpio_pin', models.IntegerField(help_text='Physical GPIO pin number')),
                ('type', models.CharField(choices=[('relay', 'Relay'), ('switch', 'Switch'), ('dht22', 'DHT22 Sensor'), ('pwm', 'PWM Output'), ('light', 'Light'), ('fan', 'Fan')], max_length=20)),
                ('default_value', models.IntegerField(default=0, help_text='Default state (0 or 1)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpio_mappings', to='devices.device')),
            ],
            options={
                'ordering': ['device', 'gpio_pin'],
                'unique_together': {('device', 'gpio_pin')},
            },
        ),
    ]
