# Generated by Django 5.2.9 on 2025-12-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AddField(
            model_name='entity',
            name='device_class',
            field=models.CharField(blank=True, help_text='Device class for sensors (e.g., temperature, humidity)', max_length=50),
        ),
        migrations.AddField(
            model_name='entity',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='friendly_name',
            field=models.CharField(blank=True, help_text='Display name (e.g., Living Room Fan)', max_length=100),
        ),
        migrations.AddField(
            model_name='entity',
            name='icon',
            field=models.CharField(blank=True, help_text='Material Design Icon (e.g., mdi:fan)', max_length=50),
        ),
        migrations.AddField(
            model_name='entity',
            name='room',
            field=models.CharField(blank=True, help_text='Room location (e.g., Living Room)', max_length=50),
        ),
        migrations.AddField(
            model_name='entity',
            name='unit_of_measurement',
            field=models.CharField(blank=True, help_text='Unit for sensors (e.g., °C, %)', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('switch', 'Switch'), ('light', 'Light'), ('fan', 'Fan'), ('sensor', 'Sensor'), ('binary_sensor', 'Binary Sensor'), ('cover', 'Cover/Blind'), ('climate', 'Climate/Thermostat'), ('lock', 'Lock'), ('button', 'Button')], max_length=20),
        ),
    ]
