# Generated by Django 5.2.9 on 2025-12-16 05:19

import apps.devices.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_entity_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_name',
            field=models.CharField(help_text='Entity name (e.g., living_room_fan). Must start with letter/underscore, contain only letters, numbers, and underscores.', max_length=50, validators=[apps.devices.validators.validate_entity_name]),
        ),
    ]
