# Generated by Django 5.2.9 on 2025-12-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_entity_entity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='close_duration',
            field=models.IntegerField(blank=True, help_text='Time to fully close in seconds (for covers/blinds)', null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='color_mode',
            field=models.CharField(blank=True, choices=[('rgb', 'RGB'), ('rgbw', 'RGBW'), ('rgbww', 'RGBWW')], help_text='Color mode for RGB lights', max_length=20),
        ),
        migrations.AddField(
            model_name='entity',
            name='hardware_type',
            field=models.CharField(blank=True, help_text="Specific hardware type (e.g., 'dht22', 'relay_active_high', 'soil_moisture_capacitive')", max_length=50),
        ),
        migrations.AddField(
            model_name='entity',
            name='i2c_address',
            field=models.CharField(blank=True, help_text="I2C address (e.g., '0x76' for BME280)", max_length=10),
        ),
        migrations.AddField(
            model_name='entity',
            name='inverted',
            field=models.BooleanField(default=False, help_text='Invert signal (for active-low relays)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='open_duration',
            field=models.IntegerField(blank=True, help_text='Time to fully open in seconds (for covers/blinds)', null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='pin_config',
            field=models.JSONField(blank=True, default=dict, help_text="Additional pins: {'sda': 21, 'scl': 22, 'red': 25, 'green': 26, 'blue': 27}"),
        ),
        migrations.AddField(
            model_name='entity',
            name='pulse_duration',
            field=models.IntegerField(blank=True, help_text='Pulse duration in milliseconds (for latching relays)', null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='supports_brightness',
            field=models.BooleanField(default=False, help_text='Supports brightness control (PWM)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='supports_color',
            field=models.BooleanField(default=False, help_text='Supports color control (RGB/RGBW)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='update_interval',
            field=models.IntegerField(default=60, help_text='Update interval in seconds (for sensors)'),
        ),
    ]
