# Generated by Django 5.2.9 on 2025-12-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_entity_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_online',
        ),
    ]
